version: '1'

services:
  web:
    build: ./orders
    command: gunicorn orders.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
    - 8000
    env_file:
      - ./orders/.env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=diplom_db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: